sudo: required
dist: trusty
language: python
git:
  depth: 10
  quiet: true
python:
  - "3.6"
env:
  matrix:
    - PROJECT="avae"
    # - PROJECT="cs_gan"  # TODO(b/184845450): Fix and re-enable
    - PROJECT="iodine"
    - PROJECT="kfac_ferminet_alpha"
    - PROJECT="learning_to_simulate"
    # - PROJECT="polygen"  # TODO(b/184847339): Fix and re-enable
    - PROJECT="transporter"
    - PROJECT="tvt"
before_script:
  - sudo apt-get update -qq
  - pip install --upgrade pip
  - pip install --upgrade virtualenv
  - pip install --upgrade wheel
script:
  - ./$PROJECT/run.sh

